name: ðŸš€ Release to NPM

on:
  release:
    types: [published]
jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "main"
          token: ${{ secrets.PAT_TOKEN }}
      - name: Install & cache node dependencies
        uses: ./.github/actions/install-node-deps
      - name: Configure Git User
        run: |
          git config --global user.email "ci@octokit.com"
          git config --global user.name "$GITHUB_ACTOR"
          git stash
          git push --delete origin ${{ github.event.release.tag_name }}
      - name: "update version"
        run: yarn lerna version ${{ github.event.release.tag_name }} --yes
      - name: Update yarn.lock with new version
        run: |
          export YARN_ENABLE_IMMUTABLE_INSTALLS=false
          yarn
          git add yarn.lock
          git commit --amend --no-edit
          git push origin --force
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./packages/event-store/package.json